// templates/react-template/src/App.tsx
function App() {
	useEffect(() => {
		const example = document.getElementById('example')
		if (example) {
			example.addEventListener('testEvent', (e) => {
				console.log('web', e)
			})
		}
	}, [])

	return (
		<>
			<div>12</div>
			<div>123</div>
			<mqy-example id="example" style={{ marginTop: '20px' }} title="Web Component" />
		</>
	)
}

export default App

// components/internal/src/App.vue
<template>
	<mqy-example id="example" style="margin-top: 20px" title="Web Component" />
</template>

<script setup lang="ts">
	onMounted(() => {
		const example = document.getElementById('example')
		if (example) {
			example.addEventListener('testEvent', (e) => {
				console.log('web', e)
			})
		}
	})
</script>

<style lang="scss" scoped></style>
