// templates/vue-template/src/pages/ErrorMessage/403.vue
<script setup lang="ts" name="403">
	import { HOME_URL } from '@/config/config'
	const router = useRouter()
</script>

<template>
	<div class="not-container">
		<span i-twemoji-construction text-40 />
		<div class="not-detail">
			<div>403</div>
			<div>抱歉，您无权访问该页面~ 🙅‍♂️🙅‍♀️</div>
			<el-button type="primary" @click="router.push(HOME_URL)"> 返回首页 </el-button>
		</div>
	</div>
</template>

<style scoped lang="scss">
	@import url('./index.scss');
</style>

// templates/react/src/pages/ErrorMessage/403.tsx
import React from 'react'
import { Button } from 'antd'
import { useNavigate } from 'react-router-dom'
import { HOME_URL } from '@/config/config'
import './index.scss'

const Forbidden: React.FC = () => {
	const navigate = useNavigate()

	return (
		<div className="not-container">
			<span className="i-twemoji-prohibited text-40" />
			<div className="not-detail">
				<div>403</div>
				<div>抱歉，您没有访问该页面的权限~</div>
				<Button type="primary" onClick={() => navigate(HOME_URL)}>
					返回首页
				</Button>
			</div>
		</div>
	)
}

export default Forbidden
