// templates/react/src/pages/ErrorMessage/404.tsx
import React from 'react'
import { Button } from 'antd'
import { useNavigate } from 'react-router-dom'
import { HOME_URL } from '@/config/config'
import './index.scss'

const NotFound: React.FC = () => {
	const navigate = useNavigate()

	return (
		<div className="not-container">
			<span className="i-twemoji-flying-saucer text-40" />
			<div className="not-detail">
				<div>404</div>
				<div>抱歉，您访问的页面不存在~ 🤷‍♂️🤷‍♀️</div>
				<Button type="primary" onClick={() => navigate(HOME_URL)}>
					返回首页
				</Button>
			</div>
		</div>
	)
}

export default NotFound

// templates/vue-template/src/pages/ErrorMessage/404.vue
<script setup lang="ts" name="404">
	import { HOME_URL } from '@/config/config'
	const router = useRouter()
</script>

<template>
	<div class="not-container">
		<span i-twemoji-flying-saucer text-40 />
		<div class="not-detail">
			<div>404</div>
			<div>抱歉，您访问的页面不存在~ 🤷‍♂️🤷‍♀️</div>
			<el-button type="primary" @click="router.push(HOME_URL)"> 返回首页 </el-button>
		</div>
	</div>
</template>

<style scoped lang="scss">
	@import url('./index.scss');
</style>
