// templates/react/src/App.tsx
import { propsEnum } from '@mqy/component-private/dist/BackgroundLayout'

function App() {
	const ref = useRef(null)
	const [isCollapse, setCollapse] = useState(false)

	const handleCustomEvent = ({ detail = [] }) => {
		console.log('web1', detail)
		switch (detail[0]) {
			case propsEnum.isCollapse:
				setCollapse(Boolean(detail[1]))
				break
		}
		// 你的逻辑
	}

	useEventListener(
		'changeProp',
		({ detail = [] }) => {
			handleCustomEvent(detail)
		},
		{ target: ref },
	)

	const { width } = useSize(document.body)!

	const getCollapse = useMemo(() => {
		return width < 1000 ? true : isCollapse
	}, [width])

	const menuList = [
		{
			path: '/',
			meta: {
				icon: 'i-mdi-alarm',
				title: '首页',
				isMenu: true,
				isViewRouter: false,
			},
			children: [
				{
					path: '/home1',
					meta: {
						icon: 'mdi mdi-account',
						title: '首页1',
						isMenu: true,
						isViewRouter: false,
					},
				},
				{
					path: '/home2',
					meta: {
						icon: 'mdi mdi-account',
						title: '首页2',
						isMenu: true,
						isViewRouter: false,
					},
				},
			],
		},
	]

	return (
		<>
			<div>react</div>
			<div>{isCollapse + ''}</div>
			<div>
				<mqy-background-layout isCollapse={false} menu-list={JSON.stringify(menuList)}>
					<div slot="body">666</div>
				</mqy-background-layout>
			</div>
		</>
	)
}

export default App

// components/private/src/App.vue
<template>
	<!--不能使用ref、不能v-modal:updateModel-->
	<!-- <mqy-example id="example" ref="mqy" title="title1" style="margin-top: 20px" /> -->
	<mqy-background-layout
		:isCollapse="themeConfig.isCollapse"
		:layout="themeConfig.layout"
		:menuList="themeConfig.menuList"
		@changeProp="handleChange"
	>
		<div slot="mqy">12我</div>
	</mqy-background-layout>
	{{ themeConfig.isCollapse }}
</template>

<script setup lang="ts">
	// import { register } from '@/components/Example'
	// register()
	const themeConfig = ref({
		isCollapse: true,
		layout: 'default',
		menuList: [
			{
				icon: 'icon-home',
				path: '/',
				meta: {
					title: '首页',
					isMenu: true,
					isViewRouter: false,
				},
				children: [
					{
						icon: 'icon-home',
						path: '/home1',
						meta: {
							title: '首页1',
							isMenu: true,
							isViewRouter: false,
						},
					},
					{
						icon: 'icon-home',
						path: '/home2',
						meta: {
							title: '首页2',
							isMenu: true,
							isViewRouter: false,
						},
					},
				],
			},
		],
	})

	const handleChange = ({ detail = [] }) => {
		console.log('web1', detail)
		// const { isCollapse } = themeConfig.value
		themeConfig.value.isCollapse = Boolean(detail[1])
		// console.log(themeConfig.value)
		// 你的逻辑
	}
</script>
