// templates/react/src/pages/ErrorMessage/500.tsx
import React from 'react'
import { Button } from 'antd'
import { useNavigate } from 'react-router-dom'
import { HOME_URL } from '@/config/config'
import './index.scss'

const ServerError: React.FC = () => {
	const navigate = useNavigate()

	return (
		<div className="not-container">
			<span className="i-twemoji-warning text-40" />
			<div className="not-detail">
				<div>500</div>
				<div>抱歉，服务器出错了~</div>
				<Button type="primary" onClick={() => navigate(HOME_URL)}>
					返回首页
				</Button>
			</div>
		</div>
	)
}

export default ServerError

// templates/vue/src/pages/ErrorMessage/500.vue
<script setup lang="ts" name="500">
	import { HOME_URL } from '@/config/config'
	const router = useRouter()
</script>

<template>
	<div class="not-container">
		<span i-twemoji-satellite-antenna text-40 />
		<div class="not-detail">
			<div>500</div>
			<div>抱歉，您的网络不见了~ 🤦‍♂️🤦‍♀️</div>
			<el-button type="primary" @click="router.push(HOME_URL)"> 返回首页 </el-button>
		</div>
	</div>
</template>

<style scoped lang="scss">
	@import url('./index.scss');
</style>
